name: publish nuget package(s) (csharp)
description: publish nuget package(s) (csharp)

inputs:
  PROJECT_FILE_PATHS:
    description: Filepath(s) to projects to build, publish, push.  CSV
    required: true
  NUGET_SOURCE:
    description: Nuget server
    required: true
  NUGET_KEY:
    description: Nuget server api key
    required: true
  VERSION_REGEX:
    description: Regex Pattern to extract version from csproj file(s)
    required: false
    default: '^.*<Version>(.*)<\/Version>.*$'
  INCLUDE_SYMBOLS:
    description: Publish symbols too?
    required: false
    default: 'false'
  TAG_COMMIT:
    description: CSV of branch names for which to tag commits
    required: false
    default: ''
  TAG_FORMAT:
    description: Tag format when tagging commits.  e.g. 'v*', where * is the version number
    required: false
    default: 'v*'
  BRANCH_VERSION_SUFFIXES:
    description: Version suffix format for branches.  e.g. 'main=-pre' for prereleases
    default: ''
    required: false
  REPO_TOKEN:
    description: 'only required when tagging secrets.GITHUB_TOKEN'
    default: ''
    required: false
runs:
  using: 'node12'
  main: 'src/index.js'